# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go build
  deploy:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run: sh ./.circleci/scripts/install_terraform.sh
      - docker-cache/build:
          command: 'echo "Starting Docker"'
      - run: sh ./.circleci/scripts/build.sh
      - run: sh ./.circleci/scripts/push.sh
      - run: sh ./.circleci/scripts/run_terraform.sh
orbs:
  aws-cli: circleci/aws-cli@1.3.0
  docker-cache: cci-x/docker-registry-image-cache@0.2.12
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - terraform